const products = [
  {
    "id": "1", 
    "product": "Moon", 
    "price": 48.33, 
    "isSale": true, 
    "isNew": true, 
    "desc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi tempore ab voluptatem eius culpa fugiat, quos sit officiis modi velit assumenda sint commodi perspiciatis est consequatur, et reiciendis minus? Harum minima a libero accusantium error, ratione soluta, praesentium deserunt ducimus cupiditate quas ab quae maxime vitae tempore ipsam voluptatum culpa pariatur, eius amet sed laborum. Repellat ex perspiciatis unde ipsum dolorum quo ea voluptatibus enim atque distinctio eligendi corporis iusto at, inventore similique explicabo magni culpa! Quaerat dolorem non nihil, nam corrupti aliquid vitae vel odio consectetur incidunt veritatis asperiores vero obcaecati nemo quasi adipisci. Debitis commodi perferendis tempora cupiditate!", 
    "img": "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Zmxvd2VyJTIwYm91cXVldHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    "category": "Bouquets", 
  },
  { 
    "id": "2", 
    "product": "Sky", 
    "price": 32.48, 
    "isSale": true, 
    "isNew": false, 
    "desc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi tempore ab voluptatem eius culpa fugiat, quos sit officiis modi velit assumenda sint commodi perspiciatis est consequatur, et reiciendis minus? Harum minima a libero accusantium error, ratione soluta, praesentium deserunt ducimus cupiditate quas ab quae maxime vitae tempore ipsam voluptatum culpa pariatur, eius amet sed laborum. Repellat ex perspiciatis unde ipsum dolorum quo ea voluptatibus enim atque distinctio eligendi corporis iusto at, inventore similique explicabo magni culpa! Quaerat dolorem non nihil, nam corrupti aliquid vitae vel odio consectetur incidunt veritatis asperiores vero obcaecati nemo quasi adipisci. Debitis commodi perferendis tempora cupiditate!", 
    "img": "https://images.unsplash.com/photo-1567418938902-aa650a3eb346?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Zmxvd2VyJTIwYm91cXVldHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    "category": "Bouquets", 
  },
  { "id": "3", 
    "product": "Belgin Night", 
    "price": 22.33, 
    "isSale": false, 
    "isNew": false, 
    "desc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi tempore ab voluptatem eius culpa fugiat, quos sit officiis modi velit assumenda sint commodi perspiciatis est consequatur, et reiciendis minus? Harum minima a libero accusantium error, ratione soluta, praesentium deserunt ducimus cupiditate quas ab quae maxime vitae tempore ipsam voluptatum culpa pariatur, eius amet sed laborum. Repellat ex perspiciatis unde ipsum dolorum quo ea voluptatibus enim atque distinctio eligendi corporis iusto at, inventore similique explicabo magni culpa! Quaerat dolorem non nihil, nam corrupti aliquid vitae vel odio consectetur incidunt veritatis asperiores vero obcaecati nemo quasi adipisci. Debitis commodi perferendis tempora cupiditate!",
    "img": "https://images.unsplash.com/photo-1583228858294-6745cb25969e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGZsb3dlciUyMGJvdXF1ZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    "category": "Bouquets", 
  },
  { 
    "id": "4", 
    "product": "Margarita", 
    "price": 31.23, 
    "isSale": false, 
    "isNew": false, 
    "desc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi tempore ab voluptatem eius culpa fugiat, quos sit officiis modi velit assumenda sint commodi perspiciatis est consequatur, et reiciendis minus? Harum minima a libero accusantium error, ratione soluta, praesentium deserunt ducimus cupiditate quas ab quae maxime vitae tempore ipsam voluptatum culpa pariatur, eius amet sed laborum. Repellat ex perspiciatis unde ipsum dolorum quo ea voluptatibus enim atque distinctio eligendi corporis iusto at, inventore similique explicabo magni culpa! Quaerat dolorem non nihil, nam corrupti aliquid vitae vel odio consectetur incidunt veritatis asperiores vero obcaecati nemo quasi adipisci. Debitis commodi perferendis tempora cupiditate!", 
    "img": "https://images.unsplash.com/photo-1571990306521-cf96e6858f2a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDR8fGZsb3dlciUyMGJvdXF1ZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
    "category": "Bouquets", 
  },
  { "id": "5", 
    "product": "Dessert Rouse", 
    "price": 33.52, 
    "isSale": false, 
    "isNew": false, 
    "desc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi tempore ab voluptatem eius culpa fugiat, quos sit officiis modi velit assumenda sint commodi perspiciatis est consequatur, et reiciendis minus? Harum minima a libero accusantium error, ratione soluta, praesentium deserunt ducimus cupiditate quas ab quae maxime vitae tempore ipsam voluptatum culpa pariatur, eius amet sed laborum. Repellat ex perspiciatis unde ipsum dolorum quo ea voluptatibus enim atque distinctio eligendi corporis iusto at, inventore similique explicabo magni culpa! Quaerat dolorem non nihil, nam corrupti aliquid vitae vel odio consectetur incidunt veritatis asperiores vero obcaecati nemo quasi adipisci. Debitis commodi perferendis tempora cupiditate!", 
    "img": "https://images.unsplash.com/photo-1523693916903-027d144a2b7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjR8fGZsb3dlciUyMGJvdXF1ZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
    "category": "Bouquets", 
  },
  { "id": "6", 
    "product": "Green Sea", 
    "price": 27.02, 
    "isSale": true, 
    "isNew": true, 
    "desc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi tempore ab voluptatem eius culpa fugiat, quos sit officiis modi velit assumenda sint commodi perspiciatis est consequatur, et reiciendis minus? Harum minima a libero accusantium error, ratione soluta, praesentium deserunt ducimus cupiditate quas ab quae maxime vitae tempore ipsam voluptatum culpa pariatur, eius amet sed laborum. Repellat ex perspiciatis unde ipsum dolorum quo ea voluptatibus enim atque distinctio eligendi corporis iusto at, inventore similique explicabo magni culpa! Quaerat dolorem non nihil, nam corrupti aliquid vitae vel odio consectetur incidunt veritatis asperiores vero obcaecati nemo quasi adipisci. Debitis commodi perferendis tempora cupiditate!", 
    "img": "https://images.unsplash.com/photo-1620752379460-d4adfe02a5ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fGZsb3dlciUyMGJvdXF1ZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
    "category": "Bouquets", 
  },

  ];

export default products;